import { UserDetails } from "./user";

export type InstituteDetails = {
  createdAt: string;
  updatedAt: string;
  instituteId: string;
  instituteCode: string;
  instituteName: string;
  displayName: string;
  instituteType: string;
  affiliationBoard: string | null;
  affiliationNumber: string | null;
  affiliationDate: string | null;
  address: string | null;
  primaryPhone: string;
  secondaryPhone: string | null;
  email: string;
  website: string | null;
  fax: string | null;
  principalName: string | null;
  principalEmail: string | null;
  principalPhone: string | null;
  founderName: string | null;
  establishmentDate: string | null;
  academicYearStartMonth: number;
  academicYearEndMonth: number;
  mediumOfInstruction: string | null;
  status: string;
  createdBy: string;
  updatedBy: string | null;
  udiseCode: string | null;
  schoolCategory: string | null;
  schoolManagement: string | null;
  hasHostelFacility: boolean;
  hasTransportFacility: boolean;
  hasCanteenFacility: boolean;
  hasSportsFacility: boolean;
  hasComputerLab: boolean;
  hasScienceLab: boolean;
  hasLibrary: boolean;
  gstNumber: string | null;
  panNumber: string | null;
  tanNumber: string | null;
  bankDetails: string | null;
  logoPath: string | null;
  instituteMotto: string | null;
  autoPromoteStudents: boolean;
  enableOnlinePayment: boolean;
  enableSmsAlerts: boolean;
  enableEmailNotifications: boolean;
  facebookUrl: string | null;
  twitterUrl: string | null;
  linkedinUrl: string | null;
  youtubeUrl: string | null;
  otherUrls: string | null;
  describeMessage: string | null;
};

export type CreateInstituteResponse = {
  instituteDetails: InstituteDetails;
  userDetails: UserDetails;
};
